[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--black --isort --verbose --ignore setup.py --cov=openapi2jsonschema --cov-report term-missing"
norecursedirs = "result"

[tool.isort]
profile = "black"
extend_skip = "result"
