[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--black --verbose --ignore setup.py --cov=openapi2jsonschema --cov-report term-missing"
